//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajecitosSAClienteConsola.CondorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vuelo", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Vuelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        private decimal ValorField;
        
        private System.DateTime HoraSalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        private int EdadUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        private System.DateTime HoraSalidaField;
        
        private int CantidadField;
        
        private decimal PrecioUnitarioField;
        
        private decimal PrecioTotalField;
        
        private System.DateTime FechaEmisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EdadUsuario {
            get {
                return this.EdadUsuarioField;
            }
            set {
                if ((this.EdadUsuarioField.Equals(value) != true)) {
                    this.EdadUsuarioField = value;
                    this.RaisePropertyChanged("EdadUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NacionalidadUsuario {
            get {
                return this.NacionalidadUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadUsuarioField, value) != true)) {
                    this.NacionalidadUsuarioField = value;
                    this.RaisePropertyChanged("NacionalidadUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal PrecioTotal {
            get {
                return this.PrecioTotalField;
            }
            set {
                if ((this.PrecioTotalField.Equals(value) != true)) {
                    this.PrecioTotalField = value;
                    this.RaisePropertyChanged("PrecioTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VueloCompraRequest", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class VueloCompraRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VueloIdField;
        
        private int UsuarioIdField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPagoField;
        
        private int NumeroCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ViajecitosSAClienteConsola.CondorService.ArrayOfString AsientosSeleccionadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VueloId {
            get {
                return this.VueloIdField;
            }
            set {
                if ((this.VueloIdField.Equals(value) != true)) {
                    this.VueloIdField = value;
                    this.RaisePropertyChanged("VueloId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoPago {
            get {
                return this.TipoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPagoField, value) != true)) {
                    this.TipoPagoField = value;
                    this.RaisePropertyChanged("TipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumeroCuotas {
            get {
                return this.NumeroCuotasField;
            }
            set {
                if ((this.NumeroCuotasField.Equals(value) != true)) {
                    this.NumeroCuotasField = value;
                    this.RaisePropertyChanged("NumeroCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ViajecitosSAClienteConsola.CondorService.ArrayOfString AsientosSeleccionados {
            get {
                return this.AsientosSeleccionadosField;
            }
            set {
                if ((object.ReferenceEquals(this.AsientosSeleccionadosField, value) != true)) {
                    this.AsientosSeleccionadosField = value;
                    this.RaisePropertyChanged("AsientosSeleccionados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://aerocondor.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amortizacion", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Amortizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int FacturaIdField;
        
        private int NumeroCuotaField;
        
        private decimal MontoCuotaField;
        
        private decimal SaldoRestanteField;
        
        private System.DateTime FechaPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int FacturaId {
            get {
                return this.FacturaIdField;
            }
            set {
                if ((this.FacturaIdField.Equals(value) != true)) {
                    this.FacturaIdField = value;
                    this.RaisePropertyChanged("FacturaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NumeroCuota {
            get {
                return this.NumeroCuotaField;
            }
            set {
                if ((this.NumeroCuotaField.Equals(value) != true)) {
                    this.NumeroCuotaField = value;
                    this.RaisePropertyChanged("NumeroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal MontoCuota {
            get {
                return this.MontoCuotaField;
            }
            set {
                if ((this.MontoCuotaField.Equals(value) != true)) {
                    this.MontoCuotaField = value;
                    this.RaisePropertyChanged("MontoCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal SaldoRestante {
            get {
                return this.SaldoRestanteField;
            }
            set {
                if ((this.SaldoRestanteField.Equals(value) != true)) {
                    this.SaldoRestanteField = value;
                    this.RaisePropertyChanged("SaldoRestante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aerocondor.com/", ConfigurationName="CondorService.CondorServiceSoap")]
    public interface CondorServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento origen del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelos", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponse ObtenerVuelos(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelos", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponse> ObtenerVuelosAsync(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComprarVueloResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelo", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ComprarVueloResponse ComprarVuelo(ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloResponse> ComprarVueloAsync(ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerVueloPorIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVueloPorId", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponse ObtenerVueloPorId(ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVueloPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponse> ObtenerVueloPorIdAsync(ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoFiltro del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelosPorFiltro", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponse ObtenerVuelosPorFiltro(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelosPorFiltro", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponse> ObtenerVuelosPorFiltroAsync(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/Login", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.LoginResponse Login(ViajecitosSAClienteConsola.CondorService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.LoginResponse> LoginAsync(ViajecitosSAClienteConsola.CondorService.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComprarVueloConCantidadResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConCantidad", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponse ComprarVueloConCantidad(ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConCantidad", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponse> ComprarVueloConCantidadAsync(ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerFacturaPorIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerFacturaPorId", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponse ObtenerFacturaPorId(ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerFacturaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponse> ObtenerFacturaPorIdAsync(ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento compras del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelosMultiples", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponse ComprarVuelosMultiples(ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelosMultiples", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponse> ComprarVuelosMultiplesAsync(ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerAmortizacionPorFacturaIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAmortizacionPorFacturaId", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponse ObtenerAmortizacionPorFacturaId(ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAmortizacionPorFacturaId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponse> ObtenerAmortizacionPorFacturaIdAsync(ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerAsientosOcupadosResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAsientosOcupados", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponse ObtenerAsientosOcupados(ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAsientosOcupados", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponse> ObtenerAsientosOcupadosAsync(ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asientosSeleccionados del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConAsientos", ReplyAction="*")]
        ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponse ComprarVueloConAsientos(ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConAsientos", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponse> ComprarVueloConAsientosAsync(ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelos", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequestBody Body;
        
        public ObtenerVuelosRequest() {
        }
        
        public ObtenerVuelosRequest(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string origen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destino;
        
        public ObtenerVuelosRequestBody() {
        }
        
        public ObtenerVuelosRequestBody(string origen, string destino) {
            this.origen = origen;
            this.destino = destino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponseBody Body;
        
        public ObtenerVuelosResponse() {
        }
        
        public ObtenerVuelosResponse(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.Vuelo[] ObtenerVuelosResult;
        
        public ObtenerVuelosResponseBody() {
        }
        
        public ObtenerVuelosResponseBody(ViajecitosSAClienteConsola.CondorService.Vuelo[] ObtenerVuelosResult) {
            this.ObtenerVuelosResult = ObtenerVuelosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelo", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVueloRequestBody Body;
        
        public ComprarVueloRequest() {
        }
        
        public ComprarVueloRequest(ViajecitosSAClienteConsola.CondorService.ComprarVueloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        public ComprarVueloRequestBody() {
        }
        
        public ComprarVueloRequestBody(int vueloId, int usuarioId) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVueloResponseBody Body;
        
        public ComprarVueloResponse() {
        }
        
        public ComprarVueloResponse(ViajecitosSAClienteConsola.CondorService.ComprarVueloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloResult;
        
        public ComprarVueloResponseBody() {
        }
        
        public ComprarVueloResponseBody(string ComprarVueloResult) {
            this.ComprarVueloResult = ComprarVueloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVueloPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVueloPorId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequestBody Body;
        
        public ObtenerVueloPorIdRequest() {
        }
        
        public ObtenerVueloPorIdRequest(ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVueloPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerVueloPorIdRequestBody() {
        }
        
        public ObtenerVueloPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVueloPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVueloPorIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponseBody Body;
        
        public ObtenerVueloPorIdResponse() {
        }
        
        public ObtenerVueloPorIdResponse(ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVueloPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.Vuelo ObtenerVueloPorIdResult;
        
        public ObtenerVueloPorIdResponseBody() {
        }
        
        public ObtenerVueloPorIdResponseBody(ViajecitosSAClienteConsola.CondorService.Vuelo ObtenerVueloPorIdResult) {
            this.ObtenerVueloPorIdResult = ObtenerVueloPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosPorFiltroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosPorFiltro", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequestBody Body;
        
        public ObtenerVuelosPorFiltroRequest() {
        }
        
        public ObtenerVuelosPorFiltroRequest(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosPorFiltroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoFiltro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valor;
        
        public ObtenerVuelosPorFiltroRequestBody() {
        }
        
        public ObtenerVuelosPorFiltroRequestBody(string tipoFiltro, string valor) {
            this.tipoFiltro = tipoFiltro;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosPorFiltroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosPorFiltroResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponseBody Body;
        
        public ObtenerVuelosPorFiltroResponse() {
        }
        
        public ObtenerVuelosPorFiltroResponse(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosPorFiltroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.Vuelo[] ObtenerVuelosPorFiltroResult;
        
        public ObtenerVuelosPorFiltroResponseBody() {
        }
        
        public ObtenerVuelosPorFiltroResponseBody(ViajecitosSAClienteConsola.CondorService.Vuelo[] ObtenerVuelosPorFiltroResult) {
            this.ObtenerVuelosPorFiltroResult = ObtenerVuelosPorFiltroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ViajecitosSAClienteConsola.CondorService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ViajecitosSAClienteConsola.CondorService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConCantidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConCantidad", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequestBody Body;
        
        public ComprarVueloConCantidadRequest() {
        }
        
        public ComprarVueloConCantidadRequest(ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConCantidadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cantidad;
        
        public ComprarVueloConCantidadRequestBody() {
        }
        
        public ComprarVueloConCantidadRequestBody(int vueloId, int usuarioId, int cantidad) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConCantidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConCantidadResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponseBody Body;
        
        public ComprarVueloConCantidadResponse() {
        }
        
        public ComprarVueloConCantidadResponse(ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConCantidadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloConCantidadResult;
        
        public ComprarVueloConCantidadResponseBody() {
        }
        
        public ComprarVueloConCantidadResponseBody(string ComprarVueloConCantidadResult) {
            this.ComprarVueloConCantidadResult = ComprarVueloConCantidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturaPorId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequestBody Body;
        
        public ObtenerFacturaPorIdRequest() {
        }
        
        public ObtenerFacturaPorIdRequest(ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerFacturaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facturaId;
        
        public ObtenerFacturaPorIdRequestBody() {
        }
        
        public ObtenerFacturaPorIdRequestBody(int facturaId) {
            this.facturaId = facturaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturaPorIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponseBody Body;
        
        public ObtenerFacturaPorIdResponse() {
        }
        
        public ObtenerFacturaPorIdResponse(ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerFacturaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.Factura ObtenerFacturaPorIdResult;
        
        public ObtenerFacturaPorIdResponseBody() {
        }
        
        public ObtenerFacturaPorIdResponseBody(ViajecitosSAClienteConsola.CondorService.Factura ObtenerFacturaPorIdResult) {
            this.ObtenerFacturaPorIdResult = ObtenerFacturaPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVuelosMultiplesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelosMultiples", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequestBody Body;
        
        public ComprarVuelosMultiplesRequest() {
        }
        
        public ComprarVuelosMultiplesRequest(ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVuelosMultiplesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.VueloCompraRequest[] compras;
        
        public ComprarVuelosMultiplesRequestBody() {
        }
        
        public ComprarVuelosMultiplesRequestBody(ViajecitosSAClienteConsola.CondorService.VueloCompraRequest[] compras) {
            this.compras = compras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVuelosMultiplesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelosMultiplesResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponseBody Body;
        
        public ComprarVuelosMultiplesResponse() {
        }
        
        public ComprarVuelosMultiplesResponse(ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVuelosMultiplesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVuelosMultiplesResult;
        
        public ComprarVuelosMultiplesResponseBody() {
        }
        
        public ComprarVuelosMultiplesResponseBody(string ComprarVuelosMultiplesResult) {
            this.ComprarVuelosMultiplesResult = ComprarVuelosMultiplesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAmortizacionPorFacturaIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAmortizacionPorFacturaId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody Body;
        
        public ObtenerAmortizacionPorFacturaIdRequest() {
        }
        
        public ObtenerAmortizacionPorFacturaIdRequest(ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAmortizacionPorFacturaIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facturaId;
        
        public ObtenerAmortizacionPorFacturaIdRequestBody() {
        }
        
        public ObtenerAmortizacionPorFacturaIdRequestBody(int facturaId) {
            this.facturaId = facturaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAmortizacionPorFacturaIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAmortizacionPorFacturaIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponseBody Body;
        
        public ObtenerAmortizacionPorFacturaIdResponse() {
        }
        
        public ObtenerAmortizacionPorFacturaIdResponse(ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAmortizacionPorFacturaIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.Amortizacion[] ObtenerAmortizacionPorFacturaIdResult;
        
        public ObtenerAmortizacionPorFacturaIdResponseBody() {
        }
        
        public ObtenerAmortizacionPorFacturaIdResponseBody(ViajecitosSAClienteConsola.CondorService.Amortizacion[] ObtenerAmortizacionPorFacturaIdResult) {
            this.ObtenerAmortizacionPorFacturaIdResult = ObtenerAmortizacionPorFacturaIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAsientosOcupadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAsientosOcupados", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequestBody Body;
        
        public ObtenerAsientosOcupadosRequest() {
        }
        
        public ObtenerAsientosOcupadosRequest(ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAsientosOcupadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        public ObtenerAsientosOcupadosRequestBody() {
        }
        
        public ObtenerAsientosOcupadosRequestBody(int vueloId) {
            this.vueloId = vueloId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAsientosOcupadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAsientosOcupadosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponseBody Body;
        
        public ObtenerAsientosOcupadosResponse() {
        }
        
        public ObtenerAsientosOcupadosResponse(ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAsientosOcupadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ArrayOfString ObtenerAsientosOcupadosResult;
        
        public ObtenerAsientosOcupadosResponseBody() {
        }
        
        public ObtenerAsientosOcupadosResponseBody(ViajecitosSAClienteConsola.CondorService.ArrayOfString ObtenerAsientosOcupadosResult) {
            this.ObtenerAsientosOcupadosResult = ObtenerAsientosOcupadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConAsientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConAsientos", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequestBody Body;
        
        public ComprarVueloConAsientosRequest() {
        }
        
        public ComprarVueloConAsientosRequest(ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConAsientosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ViajecitosSAClienteConsola.CondorService.ArrayOfString asientosSeleccionados;
        
        public ComprarVueloConAsientosRequestBody() {
        }
        
        public ComprarVueloConAsientosRequestBody(int vueloId, int usuarioId, ViajecitosSAClienteConsola.CondorService.ArrayOfString asientosSeleccionados) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
            this.asientosSeleccionados = asientosSeleccionados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConAsientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConAsientosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponseBody Body;
        
        public ComprarVueloConAsientosResponse() {
        }
        
        public ComprarVueloConAsientosResponse(ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConAsientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloConAsientosResult;
        
        public ComprarVueloConAsientosResponseBody() {
        }
        
        public ComprarVueloConAsientosResponseBody(string ComprarVueloConAsientosResult) {
            this.ComprarVueloConAsientosResult = ComprarVueloConAsientosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CondorServiceSoapChannel : ViajecitosSAClienteConsola.CondorService.CondorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CondorServiceSoapClient : System.ServiceModel.ClientBase<ViajecitosSAClienteConsola.CondorService.CondorServiceSoap>, ViajecitosSAClienteConsola.CondorService.CondorServiceSoap {
        
        public CondorServiceSoapClient() {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerVuelos(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest request) {
            return base.Channel.ObtenerVuelos(request);
        }
        
        public ViajecitosSAClienteConsola.CondorService.Vuelo[] ObtenerVuelos(string origen, string destino) {
            ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequestBody();
            inValue.Body.origen = origen;
            inValue.Body.destino = destino;
            ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerVuelos(inValue);
            return retVal.Body.ObtenerVuelosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerVuelosAsync(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest request) {
            return base.Channel.ObtenerVuelosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVuelosResponse> ObtenerVuelosAsync(string origen, string destino) {
            ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosRequestBody();
            inValue.Body.origen = origen;
            inValue.Body.destino = destino;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerVuelosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ComprarVueloResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVuelo(ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest request) {
            return base.Channel.ComprarVuelo(request);
        }
        
        public string ComprarVuelo(int vueloId, int usuarioId) {
            ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVueloRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            ViajecitosSAClienteConsola.CondorService.ComprarVueloResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVuelo(inValue);
            return retVal.Body.ComprarVueloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVueloAsync(ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest request) {
            return base.Channel.ComprarVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloResponse> ComprarVueloAsync(int vueloId, int usuarioId) {
            ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVueloRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVueloRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerVueloPorId(ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest request) {
            return base.Channel.ObtenerVueloPorId(request);
        }
        
        public ViajecitosSAClienteConsola.CondorService.Vuelo ObtenerVueloPorId(int id) {
            ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequestBody();
            inValue.Body.id = id;
            ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerVueloPorId(inValue);
            return retVal.Body.ObtenerVueloPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerVueloPorIdAsync(ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest request) {
            return base.Channel.ObtenerVueloPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdResponse> ObtenerVueloPorIdAsync(int id) {
            ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerVueloPorIdRequestBody();
            inValue.Body.id = id;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerVueloPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerVuelosPorFiltro(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest request) {
            return base.Channel.ObtenerVuelosPorFiltro(request);
        }
        
        public ViajecitosSAClienteConsola.CondorService.Vuelo[] ObtenerVuelosPorFiltro(string tipoFiltro, string valor) {
            ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequestBody();
            inValue.Body.tipoFiltro = tipoFiltro;
            inValue.Body.valor = valor;
            ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerVuelosPorFiltro(inValue);
            return retVal.Body.ObtenerVuelosPorFiltroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerVuelosPorFiltroAsync(ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest request) {
            return base.Channel.ObtenerVuelosPorFiltroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroResponse> ObtenerVuelosPorFiltroAsync(string tipoFiltro, string valor) {
            ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerVuelosPorFiltroRequestBody();
            inValue.Body.tipoFiltro = tipoFiltro;
            inValue.Body.valor = valor;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerVuelosPorFiltroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.LoginResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.Login(ViajecitosSAClienteConsola.CondorService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            ViajecitosSAClienteConsola.CondorService.LoginRequest inValue = new ViajecitosSAClienteConsola.CondorService.LoginRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ViajecitosSAClienteConsola.CondorService.LoginResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.LoginResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.LoginAsync(ViajecitosSAClienteConsola.CondorService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.LoginResponse> LoginAsync(string username, string password) {
            ViajecitosSAClienteConsola.CondorService.LoginRequest inValue = new ViajecitosSAClienteConsola.CondorService.LoginRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVueloConCantidad(ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest request) {
            return base.Channel.ComprarVueloConCantidad(request);
        }
        
        public string ComprarVueloConCantidad(int vueloId, int usuarioId, int cantidad) {
            ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.cantidad = cantidad;
            ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVueloConCantidad(inValue);
            return retVal.Body.ComprarVueloConCantidadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVueloConCantidadAsync(ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest request) {
            return base.Channel.ComprarVueloConCantidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadResponse> ComprarVueloConCantidadAsync(int vueloId, int usuarioId, int cantidad) {
            ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConCantidadRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.cantidad = cantidad;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVueloConCantidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerFacturaPorId(ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest request) {
            return base.Channel.ObtenerFacturaPorId(request);
        }
        
        public ViajecitosSAClienteConsola.CondorService.Factura ObtenerFacturaPorId(int facturaId) {
            ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequestBody();
            inValue.Body.facturaId = facturaId;
            ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerFacturaPorId(inValue);
            return retVal.Body.ObtenerFacturaPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerFacturaPorIdAsync(ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest request) {
            return base.Channel.ObtenerFacturaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdResponse> ObtenerFacturaPorIdAsync(int facturaId) {
            ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerFacturaPorIdRequestBody();
            inValue.Body.facturaId = facturaId;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerFacturaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVuelosMultiples(ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest request) {
            return base.Channel.ComprarVuelosMultiples(request);
        }
        
        public string ComprarVuelosMultiples(ViajecitosSAClienteConsola.CondorService.VueloCompraRequest[] compras) {
            ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequestBody();
            inValue.Body.compras = compras;
            ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVuelosMultiples(inValue);
            return retVal.Body.ComprarVuelosMultiplesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVuelosMultiplesAsync(ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest request) {
            return base.Channel.ComprarVuelosMultiplesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesResponse> ComprarVuelosMultiplesAsync(ViajecitosSAClienteConsola.CondorService.VueloCompraRequest[] compras) {
            ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVuelosMultiplesRequestBody();
            inValue.Body.compras = compras;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVuelosMultiplesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerAmortizacionPorFacturaId(ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest request) {
            return base.Channel.ObtenerAmortizacionPorFacturaId(request);
        }
        
        public ViajecitosSAClienteConsola.CondorService.Amortizacion[] ObtenerAmortizacionPorFacturaId(int facturaId) {
            ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody();
            inValue.Body.facturaId = facturaId;
            ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerAmortizacionPorFacturaId(inValue);
            return retVal.Body.ObtenerAmortizacionPorFacturaIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerAmortizacionPorFacturaIdAsync(ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest request) {
            return base.Channel.ObtenerAmortizacionPorFacturaIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdResponse> ObtenerAmortizacionPorFacturaIdAsync(int facturaId) {
            ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody();
            inValue.Body.facturaId = facturaId;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerAmortizacionPorFacturaIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerAsientosOcupados(ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest request) {
            return base.Channel.ObtenerAsientosOcupados(request);
        }
        
        public ViajecitosSAClienteConsola.CondorService.ArrayOfString ObtenerAsientosOcupados(int vueloId) {
            ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequestBody();
            inValue.Body.vueloId = vueloId;
            ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerAsientosOcupados(inValue);
            return retVal.Body.ObtenerAsientosOcupadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ObtenerAsientosOcupadosAsync(ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest request) {
            return base.Channel.ObtenerAsientosOcupadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosResponse> ObtenerAsientosOcupadosAsync(int vueloId) {
            ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest inValue = new ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ObtenerAsientosOcupadosRequestBody();
            inValue.Body.vueloId = vueloId;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ObtenerAsientosOcupadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponse ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVueloConAsientos(ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest request) {
            return base.Channel.ComprarVueloConAsientos(request);
        }
        
        public string ComprarVueloConAsientos(int vueloId, int usuarioId, ViajecitosSAClienteConsola.CondorService.ArrayOfString asientosSeleccionados) {
            ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.asientosSeleccionados = asientosSeleccionados;
            ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponse retVal = ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVueloConAsientos(inValue);
            return retVal.Body.ComprarVueloConAsientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponse> ViajecitosSAClienteConsola.CondorService.CondorServiceSoap.ComprarVueloConAsientosAsync(ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest request) {
            return base.Channel.ComprarVueloConAsientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosResponse> ComprarVueloConAsientosAsync(int vueloId, int usuarioId, ViajecitosSAClienteConsola.CondorService.ArrayOfString asientosSeleccionados) {
            ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest inValue = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequest();
            inValue.Body = new ViajecitosSAClienteConsola.CondorService.ComprarVueloConAsientosRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.asientosSeleccionados = asientosSeleccionados;
            return ((ViajecitosSAClienteConsola.CondorService.CondorServiceSoap)(this)).ComprarVueloConAsientosAsync(inValue);
        }
    }
}
