//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajecitosSAClienteEscritorio.CondorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vuelo", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Vuelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        private decimal ValorField;
        
        private System.DateTime HoraSalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        private int EdadUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        private System.DateTime HoraSalidaField;
        
        private int CantidadField;
        
        private decimal PrecioUnitarioField;
        
        private decimal PrecioTotalField;
        
        private System.DateTime FechaEmisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EdadUsuario {
            get {
                return this.EdadUsuarioField;
            }
            set {
                if ((this.EdadUsuarioField.Equals(value) != true)) {
                    this.EdadUsuarioField = value;
                    this.RaisePropertyChanged("EdadUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NacionalidadUsuario {
            get {
                return this.NacionalidadUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadUsuarioField, value) != true)) {
                    this.NacionalidadUsuarioField = value;
                    this.RaisePropertyChanged("NacionalidadUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal PrecioTotal {
            get {
                return this.PrecioTotalField;
            }
            set {
                if ((this.PrecioTotalField.Equals(value) != true)) {
                    this.PrecioTotalField = value;
                    this.RaisePropertyChanged("PrecioTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VueloCompraRequest", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class VueloCompraRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VueloIdField;
        
        private int UsuarioIdField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPagoField;
        
        private int NumeroCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ViajecitosSAClienteEscritorio.CondorService.ArrayOfString AsientosSeleccionadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VueloId {
            get {
                return this.VueloIdField;
            }
            set {
                if ((this.VueloIdField.Equals(value) != true)) {
                    this.VueloIdField = value;
                    this.RaisePropertyChanged("VueloId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoPago {
            get {
                return this.TipoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPagoField, value) != true)) {
                    this.TipoPagoField = value;
                    this.RaisePropertyChanged("TipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumeroCuotas {
            get {
                return this.NumeroCuotasField;
            }
            set {
                if ((this.NumeroCuotasField.Equals(value) != true)) {
                    this.NumeroCuotasField = value;
                    this.RaisePropertyChanged("NumeroCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ViajecitosSAClienteEscritorio.CondorService.ArrayOfString AsientosSeleccionados {
            get {
                return this.AsientosSeleccionadosField;
            }
            set {
                if ((object.ReferenceEquals(this.AsientosSeleccionadosField, value) != true)) {
                    this.AsientosSeleccionadosField = value;
                    this.RaisePropertyChanged("AsientosSeleccionados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://aerocondor.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amortizacion", Namespace="http://aerocondor.com/")]
    [System.SerializableAttribute()]
    public partial class Amortizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int FacturaIdField;
        
        private int NumeroCuotaField;
        
        private decimal MontoCuotaField;
        
        private decimal SaldoRestanteField;
        
        private System.DateTime FechaPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int FacturaId {
            get {
                return this.FacturaIdField;
            }
            set {
                if ((this.FacturaIdField.Equals(value) != true)) {
                    this.FacturaIdField = value;
                    this.RaisePropertyChanged("FacturaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NumeroCuota {
            get {
                return this.NumeroCuotaField;
            }
            set {
                if ((this.NumeroCuotaField.Equals(value) != true)) {
                    this.NumeroCuotaField = value;
                    this.RaisePropertyChanged("NumeroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal MontoCuota {
            get {
                return this.MontoCuotaField;
            }
            set {
                if ((this.MontoCuotaField.Equals(value) != true)) {
                    this.MontoCuotaField = value;
                    this.RaisePropertyChanged("MontoCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal SaldoRestante {
            get {
                return this.SaldoRestanteField;
            }
            set {
                if ((this.SaldoRestanteField.Equals(value) != true)) {
                    this.SaldoRestanteField = value;
                    this.RaisePropertyChanged("SaldoRestante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aerocondor.com/", ConfigurationName="CondorService.CondorServiceSoap")]
    public interface CondorServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento origen del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelos", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse ObtenerVuelos(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelos", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse> ObtenerVuelosAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComprarVueloResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelo", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse ComprarVuelo(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse> ComprarVueloAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerVueloPorIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVueloPorId", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse ObtenerVueloPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVueloPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse> ObtenerVueloPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoFiltro del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelosPorFiltro", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse ObtenerVuelosPorFiltro(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerVuelosPorFiltro", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse> ObtenerVuelosPorFiltroAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/Login", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.LoginResponse Login(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.LoginResponse> LoginAsync(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComprarVueloConCantidadResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConCantidad", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse ComprarVueloConCantidad(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConCantidad", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse> ComprarVueloConCantidadAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerFacturaPorIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerFacturaPorId", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse ObtenerFacturaPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerFacturaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse> ObtenerFacturaPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento compras del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelosMultiples", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponse ComprarVuelosMultiples(ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVuelosMultiples", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponse> ComprarVuelosMultiplesAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerAmortizacionPorFacturaIdResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAmortizacionPorFacturaId", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponse ObtenerAmortizacionPorFacturaId(ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAmortizacionPorFacturaId", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponse> ObtenerAmortizacionPorFacturaIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerAsientosOcupadosResult del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAsientosOcupados", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponse ObtenerAsientosOcupados(ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ObtenerAsientosOcupados", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponse> ObtenerAsientosOcupadosAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asientosSeleccionados del espacio de nombres http://aerocondor.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConAsientos", ReplyAction="*")]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponse ComprarVueloConAsientos(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aerocondor.com/ComprarVueloConAsientos", ReplyAction="*")]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponse> ComprarVueloConAsientosAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelos", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody Body;
        
        public ObtenerVuelosRequest() {
        }
        
        public ObtenerVuelosRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string origen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destino;
        
        public ObtenerVuelosRequestBody() {
        }
        
        public ObtenerVuelosRequestBody(string origen, string destino) {
            this.origen = origen;
            this.destino = destino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponseBody Body;
        
        public ObtenerVuelosResponse() {
        }
        
        public ObtenerVuelosResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosResult;
        
        public ObtenerVuelosResponseBody() {
        }
        
        public ObtenerVuelosResponseBody(ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosResult) {
            this.ObtenerVuelosResult = ObtenerVuelosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelo", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody Body;
        
        public ComprarVueloRequest() {
        }
        
        public ComprarVueloRequest(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        public ComprarVueloRequestBody() {
        }
        
        public ComprarVueloRequestBody(int vueloId, int usuarioId) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponseBody Body;
        
        public ComprarVueloResponse() {
        }
        
        public ComprarVueloResponse(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloResult;
        
        public ComprarVueloResponseBody() {
        }
        
        public ComprarVueloResponseBody(string ComprarVueloResult) {
            this.ComprarVueloResult = ComprarVueloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVueloPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVueloPorId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody Body;
        
        public ObtenerVueloPorIdRequest() {
        }
        
        public ObtenerVueloPorIdRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVueloPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerVueloPorIdRequestBody() {
        }
        
        public ObtenerVueloPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVueloPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVueloPorIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponseBody Body;
        
        public ObtenerVueloPorIdResponse() {
        }
        
        public ObtenerVueloPorIdResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVueloPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo ObtenerVueloPorIdResult;
        
        public ObtenerVueloPorIdResponseBody() {
        }
        
        public ObtenerVueloPorIdResponseBody(ViajecitosSAClienteEscritorio.CondorService.Vuelo ObtenerVueloPorIdResult) {
            this.ObtenerVueloPorIdResult = ObtenerVueloPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosPorFiltroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosPorFiltro", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody Body;
        
        public ObtenerVuelosPorFiltroRequest() {
        }
        
        public ObtenerVuelosPorFiltroRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosPorFiltroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoFiltro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valor;
        
        public ObtenerVuelosPorFiltroRequestBody() {
        }
        
        public ObtenerVuelosPorFiltroRequestBody(string tipoFiltro, string valor) {
            this.tipoFiltro = tipoFiltro;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerVuelosPorFiltroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerVuelosPorFiltroResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponseBody Body;
        
        public ObtenerVuelosPorFiltroResponse() {
        }
        
        public ObtenerVuelosPorFiltroResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerVuelosPorFiltroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosPorFiltroResult;
        
        public ObtenerVuelosPorFiltroResponseBody() {
        }
        
        public ObtenerVuelosPorFiltroResponseBody(ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosPorFiltroResult) {
            this.ObtenerVuelosPorFiltroResult = ObtenerVuelosPorFiltroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ViajecitosSAClienteEscritorio.CondorService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConCantidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConCantidad", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody Body;
        
        public ComprarVueloConCantidadRequest() {
        }
        
        public ComprarVueloConCantidadRequest(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConCantidadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cantidad;
        
        public ComprarVueloConCantidadRequestBody() {
        }
        
        public ComprarVueloConCantidadRequestBody(int vueloId, int usuarioId, int cantidad) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConCantidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConCantidadResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponseBody Body;
        
        public ComprarVueloConCantidadResponse() {
        }
        
        public ComprarVueloConCantidadResponse(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConCantidadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloConCantidadResult;
        
        public ComprarVueloConCantidadResponseBody() {
        }
        
        public ComprarVueloConCantidadResponseBody(string ComprarVueloConCantidadResult) {
            this.ComprarVueloConCantidadResult = ComprarVueloConCantidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturaPorId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody Body;
        
        public ObtenerFacturaPorIdRequest() {
        }
        
        public ObtenerFacturaPorIdRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerFacturaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facturaId;
        
        public ObtenerFacturaPorIdRequestBody() {
        }
        
        public ObtenerFacturaPorIdRequestBody(int facturaId) {
            this.facturaId = facturaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturaPorIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponseBody Body;
        
        public ObtenerFacturaPorIdResponse() {
        }
        
        public ObtenerFacturaPorIdResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerFacturaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Factura ObtenerFacturaPorIdResult;
        
        public ObtenerFacturaPorIdResponseBody() {
        }
        
        public ObtenerFacturaPorIdResponseBody(ViajecitosSAClienteEscritorio.CondorService.Factura ObtenerFacturaPorIdResult) {
            this.ObtenerFacturaPorIdResult = ObtenerFacturaPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVuelosMultiplesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelosMultiples", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequestBody Body;
        
        public ComprarVuelosMultiplesRequest() {
        }
        
        public ComprarVuelosMultiplesRequest(ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVuelosMultiplesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.VueloCompraRequest[] compras;
        
        public ComprarVuelosMultiplesRequestBody() {
        }
        
        public ComprarVuelosMultiplesRequestBody(ViajecitosSAClienteEscritorio.CondorService.VueloCompraRequest[] compras) {
            this.compras = compras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVuelosMultiplesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVuelosMultiplesResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponseBody Body;
        
        public ComprarVuelosMultiplesResponse() {
        }
        
        public ComprarVuelosMultiplesResponse(ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVuelosMultiplesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVuelosMultiplesResult;
        
        public ComprarVuelosMultiplesResponseBody() {
        }
        
        public ComprarVuelosMultiplesResponseBody(string ComprarVuelosMultiplesResult) {
            this.ComprarVuelosMultiplesResult = ComprarVuelosMultiplesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAmortizacionPorFacturaIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAmortizacionPorFacturaId", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody Body;
        
        public ObtenerAmortizacionPorFacturaIdRequest() {
        }
        
        public ObtenerAmortizacionPorFacturaIdRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAmortizacionPorFacturaIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facturaId;
        
        public ObtenerAmortizacionPorFacturaIdRequestBody() {
        }
        
        public ObtenerAmortizacionPorFacturaIdRequestBody(int facturaId) {
            this.facturaId = facturaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAmortizacionPorFacturaIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAmortizacionPorFacturaIdResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponseBody Body;
        
        public ObtenerAmortizacionPorFacturaIdResponse() {
        }
        
        public ObtenerAmortizacionPorFacturaIdResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAmortizacionPorFacturaIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.Amortizacion[] ObtenerAmortizacionPorFacturaIdResult;
        
        public ObtenerAmortizacionPorFacturaIdResponseBody() {
        }
        
        public ObtenerAmortizacionPorFacturaIdResponseBody(ViajecitosSAClienteEscritorio.CondorService.Amortizacion[] ObtenerAmortizacionPorFacturaIdResult) {
            this.ObtenerAmortizacionPorFacturaIdResult = ObtenerAmortizacionPorFacturaIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAsientosOcupadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAsientosOcupados", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequestBody Body;
        
        public ObtenerAsientosOcupadosRequest() {
        }
        
        public ObtenerAsientosOcupadosRequest(ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAsientosOcupadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        public ObtenerAsientosOcupadosRequestBody() {
        }
        
        public ObtenerAsientosOcupadosRequestBody(int vueloId) {
            this.vueloId = vueloId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAsientosOcupadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAsientosOcupadosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponseBody Body;
        
        public ObtenerAsientosOcupadosResponse() {
        }
        
        public ObtenerAsientosOcupadosResponse(ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ObtenerAsientosOcupadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ArrayOfString ObtenerAsientosOcupadosResult;
        
        public ObtenerAsientosOcupadosResponseBody() {
        }
        
        public ObtenerAsientosOcupadosResponseBody(ViajecitosSAClienteEscritorio.CondorService.ArrayOfString ObtenerAsientosOcupadosResult) {
            this.ObtenerAsientosOcupadosResult = ObtenerAsientosOcupadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConAsientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConAsientos", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequestBody Body;
        
        public ComprarVueloConAsientosRequest() {
        }
        
        public ComprarVueloConAsientosRequest(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConAsientosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vueloId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ViajecitosSAClienteEscritorio.CondorService.ArrayOfString asientosSeleccionados;
        
        public ComprarVueloConAsientosRequestBody() {
        }
        
        public ComprarVueloConAsientosRequestBody(int vueloId, int usuarioId, ViajecitosSAClienteEscritorio.CondorService.ArrayOfString asientosSeleccionados) {
            this.vueloId = vueloId;
            this.usuarioId = usuarioId;
            this.asientosSeleccionados = asientosSeleccionados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarVueloConAsientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprarVueloConAsientosResponse", Namespace="http://aerocondor.com/", Order=0)]
        public ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponseBody Body;
        
        public ComprarVueloConAsientosResponse() {
        }
        
        public ComprarVueloConAsientosResponse(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aerocondor.com/")]
    public partial class ComprarVueloConAsientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComprarVueloConAsientosResult;
        
        public ComprarVueloConAsientosResponseBody() {
        }
        
        public ComprarVueloConAsientosResponseBody(string ComprarVueloConAsientosResult) {
            this.ComprarVueloConAsientosResult = ComprarVueloConAsientosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CondorServiceSoapChannel : ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CondorServiceSoapClient : System.ServiceModel.ClientBase<ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap>, ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap {
        
        public CondorServiceSoapClient() {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelos(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request) {
            return base.Channel.ObtenerVuelos(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelos(string origen, string destino) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody();
            inValue.Body.origen = origen;
            inValue.Body.destino = destino;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelos(inValue);
            return retVal.Body.ObtenerVuelosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelosAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest request) {
            return base.Channel.ObtenerVuelosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosResponse> ObtenerVuelosAsync(string origen, string destino) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosRequestBody();
            inValue.Body.origen = origen;
            inValue.Body.destino = destino;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVuelo(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request) {
            return base.Channel.ComprarVuelo(request);
        }
        
        public string ComprarVuelo(int vueloId, int usuarioId) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVuelo(inValue);
            return retVal.Body.ComprarVueloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest request) {
            return base.Channel.ComprarVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloResponse> ComprarVueloAsync(int vueloId, int usuarioId) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVueloPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request) {
            return base.Channel.ObtenerVueloPorId(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo ObtenerVueloPorId(int id) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody();
            inValue.Body.id = id;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVueloPorId(inValue);
            return retVal.Body.ObtenerVueloPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVueloPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest request) {
            return base.Channel.ObtenerVueloPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdResponse> ObtenerVueloPorIdAsync(int id) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVueloPorIdRequestBody();
            inValue.Body.id = id;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVueloPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelosPorFiltro(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request) {
            return base.Channel.ObtenerVuelosPorFiltro(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Vuelo[] ObtenerVuelosPorFiltro(string tipoFiltro, string valor) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody();
            inValue.Body.tipoFiltro = tipoFiltro;
            inValue.Body.valor = valor;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelosPorFiltro(inValue);
            return retVal.Body.ObtenerVuelosPorFiltroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerVuelosPorFiltroAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest request) {
            return base.Channel.ObtenerVuelosPorFiltroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroResponse> ObtenerVuelosPorFiltroAsync(string tipoFiltro, string valor) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerVuelosPorFiltroRequestBody();
            inValue.Body.tipoFiltro = tipoFiltro;
            inValue.Body.valor = valor;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerVuelosPorFiltroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.LoginResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.Login(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            ViajecitosSAClienteEscritorio.CondorService.LoginRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.LoginRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ViajecitosSAClienteEscritorio.CondorService.LoginResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.LoginResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.LoginAsync(ViajecitosSAClienteEscritorio.CondorService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.LoginResponse> LoginAsync(string username, string password) {
            ViajecitosSAClienteEscritorio.CondorService.LoginRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.LoginRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloConCantidad(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request) {
            return base.Channel.ComprarVueloConCantidad(request);
        }
        
        public string ComprarVueloConCantidad(int vueloId, int usuarioId, int cantidad) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.cantidad = cantidad;
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloConCantidad(inValue);
            return retVal.Body.ComprarVueloConCantidadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloConCantidadAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest request) {
            return base.Channel.ComprarVueloConCantidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadResponse> ComprarVueloConCantidadAsync(int vueloId, int usuarioId, int cantidad) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConCantidadRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.cantidad = cantidad;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloConCantidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerFacturaPorId(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request) {
            return base.Channel.ObtenerFacturaPorId(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Factura ObtenerFacturaPorId(int facturaId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody();
            inValue.Body.facturaId = facturaId;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerFacturaPorId(inValue);
            return retVal.Body.ObtenerFacturaPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerFacturaPorIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest request) {
            return base.Channel.ObtenerFacturaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdResponse> ObtenerFacturaPorIdAsync(int facturaId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerFacturaPorIdRequestBody();
            inValue.Body.facturaId = facturaId;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerFacturaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVuelosMultiples(ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest request) {
            return base.Channel.ComprarVuelosMultiples(request);
        }
        
        public string ComprarVuelosMultiples(ViajecitosSAClienteEscritorio.CondorService.VueloCompraRequest[] compras) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequestBody();
            inValue.Body.compras = compras;
            ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVuelosMultiples(inValue);
            return retVal.Body.ComprarVuelosMultiplesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVuelosMultiplesAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest request) {
            return base.Channel.ComprarVuelosMultiplesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesResponse> ComprarVuelosMultiplesAsync(ViajecitosSAClienteEscritorio.CondorService.VueloCompraRequest[] compras) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVuelosMultiplesRequestBody();
            inValue.Body.compras = compras;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVuelosMultiplesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerAmortizacionPorFacturaId(ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest request) {
            return base.Channel.ObtenerAmortizacionPorFacturaId(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.Amortizacion[] ObtenerAmortizacionPorFacturaId(int facturaId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody();
            inValue.Body.facturaId = facturaId;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerAmortizacionPorFacturaId(inValue);
            return retVal.Body.ObtenerAmortizacionPorFacturaIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerAmortizacionPorFacturaIdAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest request) {
            return base.Channel.ObtenerAmortizacionPorFacturaIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdResponse> ObtenerAmortizacionPorFacturaIdAsync(int facturaId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAmortizacionPorFacturaIdRequestBody();
            inValue.Body.facturaId = facturaId;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerAmortizacionPorFacturaIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerAsientosOcupados(ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest request) {
            return base.Channel.ObtenerAsientosOcupados(request);
        }
        
        public ViajecitosSAClienteEscritorio.CondorService.ArrayOfString ObtenerAsientosOcupados(int vueloId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequestBody();
            inValue.Body.vueloId = vueloId;
            ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerAsientosOcupados(inValue);
            return retVal.Body.ObtenerAsientosOcupadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ObtenerAsientosOcupadosAsync(ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest request) {
            return base.Channel.ObtenerAsientosOcupadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosResponse> ObtenerAsientosOcupadosAsync(int vueloId) {
            ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ObtenerAsientosOcupadosRequestBody();
            inValue.Body.vueloId = vueloId;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ObtenerAsientosOcupadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponse ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloConAsientos(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest request) {
            return base.Channel.ComprarVueloConAsientos(request);
        }
        
        public string ComprarVueloConAsientos(int vueloId, int usuarioId, ViajecitosSAClienteEscritorio.CondorService.ArrayOfString asientosSeleccionados) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.asientosSeleccionados = asientosSeleccionados;
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponse retVal = ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloConAsientos(inValue);
            return retVal.Body.ComprarVueloConAsientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponse> ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap.ComprarVueloConAsientosAsync(ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest request) {
            return base.Channel.ComprarVueloConAsientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosResponse> ComprarVueloConAsientosAsync(int vueloId, int usuarioId, ViajecitosSAClienteEscritorio.CondorService.ArrayOfString asientosSeleccionados) {
            ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest inValue = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequest();
            inValue.Body = new ViajecitosSAClienteEscritorio.CondorService.ComprarVueloConAsientosRequestBody();
            inValue.Body.vueloId = vueloId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.asientosSeleccionados = asientosSeleccionados;
            return ((ViajecitosSAClienteEscritorio.CondorService.CondorServiceSoap)(this)).ComprarVueloConAsientosAsync(inValue);
        }
    }
}
